media:
  input: assets/uploads
  output: /assets/uploads

content:
  - name: news
    label: Tilkynningar
    type: file
    path: data/news.json
    fields:
      - name: items
        label: Tilkynningar og tilboð
        type: object
        list: true
        fields:
          - name: title
            label: Titill
            type: string
            required: true
          - name: date
            label: Dagsetning
            type: date
          - name: body
            label: Texti
            type: text

  - name: staff
    label: Starfsfólk
    type: file
    path: data/staff.json
    fields:
      - name: members
        label: Starfsmenn
        type: object
        list: true
        fields:
          - name: name
            label: Nafn
            type: string
            required: true
          - name: title
            label: Starfsheiti
            type: string
            default: Sjúkraþjálfari
          - name: photo
            label: Mynd
            type: image
          - name: on_leave
            label: Í fæðingarorlofi
            type: boolean
